name:         The Once And Future Code.
pygments:     true
description:  Just another Jekyll blog.
url:          http://blog.atomsign.net
asciidoc:     asciidoctor
asciidoc_ext: asciidoc,adoc
timeszone:    America/Los_Angeles
