# Site settings
name:         "Alan Fung-Schwarz"
title:        "The Once And Future Code."
email:        "alan@atomsign.net"
description:  "Another Jekyll blog."
url:          "http://blog.atomsign.net"
baseurl:      ""
asciidoc:     asciidoctor
asciidoc_ext: asciidoc,adoc
timezone:     "America/Los_Angeles"

# Build settings
markdown: kramdown
permalink: pretty
highlighter:  pygments
sass:
  style: compressed

twitter: ajcfs
github: alanjcfs

gems: [RedCloth]
